package com.steelypip.powerups.exceptions;

import junit.framework.TestCase;

public class TestExceptions extends TestCase {
	void testAlert() {
		fail();
	}
}
